pages/ui/Cooldown.tsx

[ADD]: Red cooldown box when maxed out

---

next-i18next.config.js
next.config.js
package-lock.json
package.json
pages/_app.page.tsx
pages/constants/languages.ts
pages/controller/ConnectionController.ts
pages/index.page.tsx
pages/ui/Chat.tsx
pages/ui/Cooldown.tsx
pages/ui/Overlay.tsx
pages/ui/modals/Captcha.tsx
pages/ui/modals/Converter.tsx
pages/ui/modals/Infos.tsx
pages/ui/modals/Parameters.tsx
public/locales/en/captcha.json
public/locales/en/common.json
public/locales/en/converter.json
public/locales/en/infos.json
public/locales/en/overlay.json
public/locales/en/parameters.json
public/locales/fr/captcha.json
public/locales/fr/common.json
public/locales/fr/converter.json
public/locales/fr/infos.json
public/locales/fr/overlay.json
public/locales/fr/parameters.json

[ADD]: i18n FR/EN

---

pages/ui/Cooldown.tsx

[ADD]: Calculate cooldown as diff of Date

---

pages/ui/modals/Captcha.tsx

[FIX]: Captcha on mobile

---

pages/controller/CanvasController.ts
pages/controller/InteractionController.ts

[FIX]: Light blue inside hover square outside of the map

---

pages/controller/CanvasController.ts
pages/controller/ConnectionController.ts
pages/ui/modals/Parameters.tsx
public/locales/en/parameters.json
public/locales/fr/parameters.json
public/locales/ptbr/parameters.json
store/actions/parameters.ts
store/index.ts

[ADD]: Pixel Activity + Activity Parameter

---

pages/controller/CanvasController.ts
pages/ui/modals/Captcha.tsx

[FIX]: Autofocus canvas on page load & after captcha

---

pages/controller/InteractionController.ts

[FIX]: Stop Long Touch from selecting text + no select color when zooming/moving

---

pages/controller/InteractionController.ts

[FIX]: Placing pixels on mobile

---

pages/constants/languages.ts
pages/controller/ConnectionController.ts
pages/ui/Modal.tsx
pages/ui/modals/Converter.tsx
pages/ui/modals/Infos.tsx
pages/ui/modals/Parameters.tsx
pages/ui/modals/Problem.tsx
pages/ui/modals/Stats.tsx
public/locales/en/converter.json
public/locales/en/problem.json
public/locales/en/stats.json
public/locales/fr/converter.json
public/locales/fr/problem.json
public/locales/fr/stats.json
public/locales/ptbr/converter.json
store/actions/user.ts

[ADD]: Pixel rankings

---

pages/constants/languages.ts
pages/controller/CanvasController.ts
pages/ui/Chat.tsx
public/locales/en/chat.json
public/locales/en/common.json
public/locales/fr/chat.json
public/locales/fr/common.json
store/actions/parameters.ts
store/index.ts

Closes #41 
*(Delayed by tati)*

[ADD]: Restrict chat only for logged

---

package-lock.json
package.json
pages/controller/CanvasController.ts
pages/ui/Chat.tsx
pages/ui/ChatFormatting.tsx
store/actions/painting.ts
store/index.ts

[ADD]: More chat features (Positions, here, help, mentions, greentext)

---

pages/controller/CanvasController.ts
pages/controller/ConnectionController.ts
pages/controller/InteractionController.ts
pages/controller/OverlayController.ts
pages/index.page.tsx
pages/ui/Alert.tsx
pages/ui/Cooldown.tsx
pages/ui/PaletteList.tsx
pages/ui/modals/Parameters.tsx
store/actions/infos.ts
store/actions/overlay.ts
store/actions/painting.ts
store/actions/parameters.ts
store/index.ts

[ADD]: New keys to move and activate options + Alert + Rendering lifecycle rework

---

pages/constants/modalTypes.ts
pages/controller/CanvasController.ts
pages/controller/OverlayController.ts
pages/ui/Modal.tsx
pages/ui/Overlay.tsx
pages/ui/modals/Overlay.tsx
public/locales/en/overlay.json
public/locales/fr/overlay.json
store/actions/overlay.ts
store/index.ts

[ADD]: Overlay options (Save, Share, Import, ...)

---

pages/ui/modals/Converter.tsx
public/locales/en/converter.json
public/locales/fr/converter.json

[ADD]: Grid option on converter

---

pages/controller/InteractionController.ts
pages/ui/ButtonList.tsx
store/actions/infos.ts
store/index.ts

[ADD]: Search box for grid position

---

pages/constants/languages.ts
pages/controller/CanvasController.ts
pages/ui/Cooldown.tsx
pages/ui/modals/Parameters.tsx
public/locales/en/notification.json
public/locales/en/parameters.json
public/locales/fr/notification.json
public/locales/fr/parameters.json
store/actions/parameters.ts
store/index.ts
store/reducer.ts

[ADD]: Notifications when pixel cooldown is finished

---

pages/ui/HistoryMode.tsx
pages/ui/modals/Parameters.tsx
public/locales/en/parameters.json
public/locales/fr/parameters.json

[FIX]: History box no display when not active + activate parameter in menu

---

pages/controller/CanvasController.ts

[FIX]: Show no pixel activity when in history mode

---

pages/controller/CanvasController.ts
pages/controller/Chunk.ts
pages/controller/ConnectionController.ts
pages/ui/HistoryMode.tsx
pages/ui/modals/Parameters.tsx
store/actions/parameters.ts
store/index.ts

[ADD]: Multicanvas + only one chunk img + some history fixes

---

pages/ui/ButtonList.tsx
pages/ui/Chat.tsx
pages/ui/CursorPosition.tsx
pages/ui/Modal.tsx
pages/ui/Overlay.tsx
pages/ui/PlayerCounter.tsx
pages/ui/modals/Converter.tsx
pages/ui/modals/Parameters.tsx
public/locales/en/parameters.json
public/locales/fr/parameters.json
store/actions/parameters.ts
store/index.ts

add dark mode

---

pages/ui/modals/Parameters.tsx
store/actions/parameters.ts

[ADD]: Recenter when changing canvas

---

pages/controller/CanvasController.ts
pages/controller/Chunk.ts
pages/controller/InteractionController.ts
pages/index.page.tsx

[ADD]: Superchunks + unlock zoom + limit position

---

pages/controller/CanvasController.ts
pages/ui/ButtonList.tsx
pages/ui/Chat.tsx
pages/ui/ChatFormatting.tsx
pages/ui/modals/Parameters.tsx
store/actions/infos.ts
store/actions/parameters.ts

[ADD]: Position tag includes canvases and zoom infos + Some render improvements

---

pages/controller/Chunk.ts
pages/controller/ConnectionController.ts

[ADD]: Refresh from WS

---

pages/controller/CanvasController.ts
pages/ui/Chat.tsx
store/actions/chat.ts
store/actions/parameters.ts
store/index.ts

[ADD]: Red bubble on unread messages

---

pages/ui/HistoryMode.tsx

[FIX]: History date timezones + keep value after closing/reopening

---

pages/controller/InteractionController.ts
pages/ui/CursorPosition.tsx

[ADD]: Copy URL with shift+c and cursor pos with C + copy pos on clicking cursor pos box

---

pages/ui/modals/Infos.tsx
public/locales/en/infos.json
public/locales/fr/infos.json

[ADD]: Hotkey list in help

---

pages/constants/modalTypes.ts
pages/controller/InteractionController.ts
pages/ui/ButtonList.tsx
pages/ui/Modal.tsx
pages/ui/modals/Bookmarks.tsx
store/actions/infos.ts

[ADD]: Bookmarks

---

pages/controller/ConnectionController.ts
pages/ui/modals/Problem.tsx
store/actions/infos.ts
store/index.ts

[ADD]: Disconnection reason for user

---

pages/controller/ConnectionController.ts
pages/ui/Alert.tsx
pages/ui/Cooldown.tsx

[ADD]: Alerts user on why they cant place pixel

---

pages/ui/Modal.tsx
styles/index.css

[FIX]: Mobile scrolling

---

pages/admin/Logs.tsx
pages/admin/MapOperations.tsx
pages/admin/[page].page.tsx
pages/admin/sidebar.tsx
pages/admin/utils.tsx

[ADD]: Admin allow copy pasting of coordinates + save page with dynamic routing

---

next.config.js
pages/admin/Activity.tsx
pages/admin/Logs.tsx
pages/admin/[page].page.tsx
pages/admin/sidebar.tsx
pages/admin/utils.tsx

[ADD]: Responsive admin tools + redirect /admin to /admin/activity

---

pages/controller/CanvasController.ts
pages/controller/InteractionController.ts

[FIX]: Zooming

---

pages/ui/modals/Captcha.tsx

[ADD]: Captcha refresh button

---

pages/ui/ChatFormatting.tsx

[ADD]: Simple markdown: Bold/Italics/Underline/Code

---

pages/ui/modals/Parameters.tsx

[ADD]: Download viewport at 1:1 in settings

---

pages/ui/ButtonList.tsx
public/locales/en/parameters.json
public/locales/fr/parameters.json
store/actions/parameters.ts
store/index.ts

[ADD]: Dropdown buttons to hide/show them

---

pages/constants/languages.ts
pages/index/store/actions/chat.ts
pages/index/ui/Chat.tsx
pages/pagesComponents.tsx
pages/user/Faction/Member.tsx
pages/user/Faction/NotMember.tsx
pages/user/Faction/index.tsx
pages/user/Settings.tsx
pages/user/[page].page.tsx
pages/user/store/actions/faction.ts
pages/user/store/actions/user.ts
pages/user/store/index.ts
pages/user/store/reducer.ts
public/locales/en/faction.json
public/locales/fr/faction.json

[ADD]: Factions interface

---

pages/index/controller/CanvasController.ts
pages/index/ui/Chat.tsx

fix: no scroll chat when not at bottom

---

pages/index.page.tsx
pages/index/controller/ConnectionController.ts
pages/index/ui/Canvas.tsx
pages/index/ui/Chat.tsx

fix: autologin when page reloads

---

pages/index/ui/modals/Moderation/index.tsx

Reverse last commit, allowing moderators to use map operations
